'use client';

import { Building2, LogOut, Mail, MapPin, ShieldCheck } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { useWorkspace } from "@/components/workspace-provider";

export default function ProfilePage() {
  const { currentUser, workspace, logout } = useWorkspace();
  return <><AppHeader title="My profile" description="Your account and workspace access." /><section className="overflow-hidden rounded-[24px] bg-primary text-white"><div className="p-5 sm:p-7"><span className="grid size-16 place-items-center rounded-[22px] bg-accent text-xl font-extrabold text-accent-ink">{currentUser?.fullName.split(" ").map((part) => part[0]).slice(0, 2).join("") ?? "SF"}</span><h2 className="mt-4 text-xl font-extrabold">{currentUser?.fullName}</h2><p className="mt-1 text-[11px] text-white/50">{currentUser?.title}</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-2"><div className="flex items-center gap-3 bg-primary p-4"><Mail className="size-4 text-accent" /><div><p className="text-[9px] uppercase text-white/40">Email</p><p className="mt-1 text-[11px] font-bold">{currentUser?.email}</p></div></div><div className="flex items-center gap-3 bg-primary p-4"><ShieldCheck className="size-4 text-accent" /><div><p className="text-[9px] uppercase text-white/40">Access</p><p className="mt-1 text-[11px] font-bold">{currentUser?.role}</p></div></div><div className="flex items-center gap-3 bg-primary p-4"><Building2 className="size-4 text-accent" /><div><p className="text-[9px] uppercase text-white/40">Business</p><p className="mt-1 text-[11px] font-bold">{workspace.settings.companyName}</p></div></div><div className="flex items-center gap-3 bg-primary p-4"><MapPin className="size-4 text-accent" /><div><p className="text-[9px] uppercase text-white/40">Location</p><p className="mt-1 text-[11px] font-bold">{currentUser?.shop}</p></div></div></div></section><button type="button" onClick={() => void logout()} className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-[16px] border border-danger/20 bg-danger/7 text-xs font-extrabold text-danger lg:w-auto lg:px-5"><LogOut className="size-4" /> Sign out securely</button></>;
}
